### ISSUE TITLE
Setup some gotbugs inception

### ISSUE THREAD

**Issue by jasonLaster** [replayio/replayable#15]
Not sure why it took me so long to realize this, but we should be documenting the issues we see in Github so that we can show these open / closed issues in gotbugs :)

https://app.replay.io/recording/got-bugs--68a71ba2-f3b8-4724-86cb-53471f4fca79

**Comment by gideonred** [comment]
This ticket has been moved to [GTM-143](https://linear.app/replay/issue/GTM-143/setup-some-gotbugs-inception)
