### ISSUE TITLE
Add loading message when fetching new results

### ISSUE THREAD

**Issue by ceceliacreates** [replayio/replayable#22]
Right now, whenever we are fetching new results, the screen is entirely black. Would be nice to have a loading message so it doesn't look broken.

https://app.replay.io/recording/got-bugs-black-screen-when-fetching--a8c73241-5f2c-4541-aa02-4e3970c317a2

**Comment by gideonred** [comment]
This ticket has been moved to [GTM-146](https://linear.app/replay/issue/GTM-146/add-loading-message-when-fetching-new-results)
